### ISSUE TITLE
Missing pom.xml

### ISSUE THREAD

**Issue by netmackan** [dorkbox/CabParser#3]
It would be useful if the pom.xml was available in the Git repository so the project could be opened directly by any Maven capable IDE. 
As you are publishing artifacts to the Central I guess you have the pom.xml anyway.

**Comment by dorkbox** [comment]
I actually generate the pom.xml files during the compile process, simply because I really dislike how maven is implemented, but I love what the service provides; which is why I publish to maven, but auto-generate all of the maven requirements.

How difficult would it be to copy the pom.xml from here for your project? 

https://oss.sonatype.org/content/repositories/releases/com/dorkbox/CabParser/2.9/CabParser-2.9.pom

**Comment by netmackan** [comment]
Okey, I see.

Personally, I would do it the other way around if I used an IDE without good Maven support but that's just because I like the common project model and the conventions it brings.
No problem for me, I actually finally got the POM from there. 
I was more thinking in terms of the convenience for potential other users/contributors.

**Comment by dorkbox** [comment]
Hm, you make a strong point... As much as I dislike it, it makes sense to include. I'll go about adding it to the source.
