### ISSUE TITLE
Sources for CabParser-Dorkbox-Util?

### ISSUE THREAD

**Issue by netmackan** [dorkbox/CabParser#4]
The sources for dorkbox.util.bytes and dorkbox.util.process are not available in the Git repository? Would it be possible to have the CabParser-Dorkbox-Util project added or is there an other repository for that project?

**Comment by dorkbox** [comment]
At this point in time, the Dorkbox-Util project is not a public repository simply because parts of it are proprietary and it is huge. The ultimate goal is to extract the more common, useful parts into their own projects as they evolve and become complete -- which is what the majority of my public repos are. The `bytes` package is high on the list, and `process` isn't complete yet (so that one will be a while, as there are some native parts that need implementation).

However, the source for what is currently available for those packages is here, just not as a git repo.  
https://oss.sonatype.org/content/repositories/releases/com/dorkbox/CabParser-Dorkbox-Util/

**Comment by netmackan** [comment]
Thank you.
